id: I28388C3B
source: https://github.com/Esukhia/chojuk-alignement/tree/master/D3872-final
source_file: null
initial_creation_type: input
imported: '2022-07-27T11:24:23.290808'
last_modified: '2022-07-27T11:24:23.290825'
parser: null
source_metadata:
  title: Commentary
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
